// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: mls_client.proto

package mlspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLSClient_Name_FullMethodName                           = "/mls_client.MLSClient/Name"
	MLSClient_SupportedCiphersuites_FullMethodName          = "/mls_client.MLSClient/SupportedCiphersuites"
	MLSClient_CreateGroup_FullMethodName                    = "/mls_client.MLSClient/CreateGroup"
	MLSClient_CreateKeyPackage_FullMethodName               = "/mls_client.MLSClient/CreateKeyPackage"
	MLSClient_JoinGroup_FullMethodName                      = "/mls_client.MLSClient/JoinGroup"
	MLSClient_ExternalJoin_FullMethodName                   = "/mls_client.MLSClient/ExternalJoin"
	MLSClient_GroupInfo_FullMethodName                      = "/mls_client.MLSClient/GroupInfo"
	MLSClient_StateAuth_FullMethodName                      = "/mls_client.MLSClient/StateAuth"
	MLSClient_Export_FullMethodName                         = "/mls_client.MLSClient/Export"
	MLSClient_Protect_FullMethodName                        = "/mls_client.MLSClient/Protect"
	MLSClient_Unprotect_FullMethodName                      = "/mls_client.MLSClient/Unprotect"
	MLSClient_StorePSK_FullMethodName                       = "/mls_client.MLSClient/StorePSK"
	MLSClient_AddProposal_FullMethodName                    = "/mls_client.MLSClient/AddProposal"
	MLSClient_UpdateProposal_FullMethodName                 = "/mls_client.MLSClient/UpdateProposal"
	MLSClient_RemoveProposal_FullMethodName                 = "/mls_client.MLSClient/RemoveProposal"
	MLSClient_ExternalPSKProposal_FullMethodName            = "/mls_client.MLSClient/ExternalPSKProposal"
	MLSClient_ResumptionPSKProposal_FullMethodName          = "/mls_client.MLSClient/ResumptionPSKProposal"
	MLSClient_GroupContextExtensionsProposal_FullMethodName = "/mls_client.MLSClient/GroupContextExtensionsProposal"
	MLSClient_Commit_FullMethodName                         = "/mls_client.MLSClient/Commit"
	MLSClient_HandleCommit_FullMethodName                   = "/mls_client.MLSClient/HandleCommit"
	MLSClient_HandlePendingCommit_FullMethodName            = "/mls_client.MLSClient/HandlePendingCommit"
	MLSClient_ReInitProposal_FullMethodName                 = "/mls_client.MLSClient/ReInitProposal"
	MLSClient_ReInitCommit_FullMethodName                   = "/mls_client.MLSClient/ReInitCommit"
	MLSClient_HandlePendingReInitCommit_FullMethodName      = "/mls_client.MLSClient/HandlePendingReInitCommit"
	MLSClient_HandleReInitCommit_FullMethodName             = "/mls_client.MLSClient/HandleReInitCommit"
	MLSClient_ReInitWelcome_FullMethodName                  = "/mls_client.MLSClient/ReInitWelcome"
	MLSClient_HandleReInitWelcome_FullMethodName            = "/mls_client.MLSClient/HandleReInitWelcome"
	MLSClient_CreateBranch_FullMethodName                   = "/mls_client.MLSClient/CreateBranch"
	MLSClient_HandleBranch_FullMethodName                   = "/mls_client.MLSClient/HandleBranch"
	MLSClient_NewMemberAddProposal_FullMethodName           = "/mls_client.MLSClient/NewMemberAddProposal"
	MLSClient_CreateExternalSigner_FullMethodName           = "/mls_client.MLSClient/CreateExternalSigner"
	MLSClient_AddExternalSigner_FullMethodName              = "/mls_client.MLSClient/AddExternalSigner"
	MLSClient_ExternalSignerProposal_FullMethodName         = "/mls_client.MLSClient/ExternalSignerProposal"
	MLSClient_Free_FullMethodName                           = "/mls_client.MLSClient/Free"
)

// MLSClientClient is the client API for MLSClient service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// A wrapper around an MLS client implementation
type MLSClientClient interface {
	// The human-readable name of the stack
	Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error)
	// List of supported ciphersuites
	SupportedCiphersuites(ctx context.Context, in *SupportedCiphersuitesRequest, opts ...grpc.CallOption) (*SupportedCiphersuitesResponse, error)
	// Ways to become a member of a group
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	CreateKeyPackage(ctx context.Context, in *CreateKeyPackageRequest, opts ...grpc.CallOption) (*CreateKeyPackageResponse, error)
	JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error)
	ExternalJoin(ctx context.Context, in *ExternalJoinRequest, opts ...grpc.CallOption) (*ExternalJoinResponse, error)
	// Operations using a group state
	GroupInfo(ctx context.Context, in *GroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error)
	StateAuth(ctx context.Context, in *StateAuthRequest, opts ...grpc.CallOption) (*StateAuthResponse, error)
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	Protect(ctx context.Context, in *ProtectRequest, opts ...grpc.CallOption) (*ProtectResponse, error)
	Unprotect(ctx context.Context, in *UnprotectRequest, opts ...grpc.CallOption) (*UnprotectResponse, error)
	StorePSK(ctx context.Context, in *StorePSKRequest, opts ...grpc.CallOption) (*StorePSKResponse, error)
	AddProposal(ctx context.Context, in *AddProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	UpdateProposal(ctx context.Context, in *UpdateProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	RemoveProposal(ctx context.Context, in *RemoveProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	ExternalPSKProposal(ctx context.Context, in *ExternalPSKProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	ResumptionPSKProposal(ctx context.Context, in *ResumptionPSKProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	GroupContextExtensionsProposal(ctx context.Context, in *GroupContextExtensionsProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	HandleCommit(ctx context.Context, in *HandleCommitRequest, opts ...grpc.CallOption) (*HandleCommitResponse, error)
	HandlePendingCommit(ctx context.Context, in *HandlePendingCommitRequest, opts ...grpc.CallOption) (*HandleCommitResponse, error)
	// Reinitialization
	ReInitProposal(ctx context.Context, in *ReInitProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	ReInitCommit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error)
	HandlePendingReInitCommit(ctx context.Context, in *HandlePendingCommitRequest, opts ...grpc.CallOption) (*HandleReInitCommitResponse, error)
	HandleReInitCommit(ctx context.Context, in *HandleCommitRequest, opts ...grpc.CallOption) (*HandleReInitCommitResponse, error)
	ReInitWelcome(ctx context.Context, in *ReInitWelcomeRequest, opts ...grpc.CallOption) (*CreateSubgroupResponse, error)
	HandleReInitWelcome(ctx context.Context, in *HandleReInitWelcomeRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error)
	// Subgroup Branching
	CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateSubgroupResponse, error)
	HandleBranch(ctx context.Context, in *HandleBranchRequest, opts ...grpc.CallOption) (*HandleBranchResponse, error)
	// External proposals
	NewMemberAddProposal(ctx context.Context, in *NewMemberAddProposalRequest, opts ...grpc.CallOption) (*NewMemberAddProposalResponse, error)
	CreateExternalSigner(ctx context.Context, in *CreateExternalSignerRequest, opts ...grpc.CallOption) (*CreateExternalSignerResponse, error)
	AddExternalSigner(ctx context.Context, in *AddExternalSignerRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	ExternalSignerProposal(ctx context.Context, in *ExternalSignerProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error)
	// Cleanup
	Free(ctx context.Context, in *FreeRequest, opts ...grpc.CallOption) (*FreeResponse, error)
}

type mLSClientClient struct {
	cc grpc.ClientConnInterface
}

func NewMLSClientClient(cc grpc.ClientConnInterface) MLSClientClient {
	return &mLSClientClient{cc}
}

func (c *mLSClientClient) Name(ctx context.Context, in *NameRequest, opts ...grpc.CallOption) (*NameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NameResponse)
	err := c.cc.Invoke(ctx, MLSClient_Name_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) SupportedCiphersuites(ctx context.Context, in *SupportedCiphersuitesRequest, opts ...grpc.CallOption) (*SupportedCiphersuitesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SupportedCiphersuitesResponse)
	err := c.cc.Invoke(ctx, MLSClient_SupportedCiphersuites_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, MLSClient_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) CreateKeyPackage(ctx context.Context, in *CreateKeyPackageRequest, opts ...grpc.CallOption) (*CreateKeyPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateKeyPackageResponse)
	err := c.cc.Invoke(ctx, MLSClient_CreateKeyPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) JoinGroup(ctx context.Context, in *JoinGroupRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupResponse)
	err := c.cc.Invoke(ctx, MLSClient_JoinGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ExternalJoin(ctx context.Context, in *ExternalJoinRequest, opts ...grpc.CallOption) (*ExternalJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalJoinResponse)
	err := c.cc.Invoke(ctx, MLSClient_ExternalJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) GroupInfo(ctx context.Context, in *GroupInfoRequest, opts ...grpc.CallOption) (*GroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GroupInfoResponse)
	err := c.cc.Invoke(ctx, MLSClient_GroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) StateAuth(ctx context.Context, in *StateAuthRequest, opts ...grpc.CallOption) (*StateAuthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StateAuthResponse)
	err := c.cc.Invoke(ctx, MLSClient_StateAuth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, MLSClient_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) Protect(ctx context.Context, in *ProtectRequest, opts ...grpc.CallOption) (*ProtectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProtectResponse)
	err := c.cc.Invoke(ctx, MLSClient_Protect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) Unprotect(ctx context.Context, in *UnprotectRequest, opts ...grpc.CallOption) (*UnprotectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnprotectResponse)
	err := c.cc.Invoke(ctx, MLSClient_Unprotect_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) StorePSK(ctx context.Context, in *StorePSKRequest, opts ...grpc.CallOption) (*StorePSKResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StorePSKResponse)
	err := c.cc.Invoke(ctx, MLSClient_StorePSK_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) AddProposal(ctx context.Context, in *AddProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_AddProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) UpdateProposal(ctx context.Context, in *UpdateProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_UpdateProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) RemoveProposal(ctx context.Context, in *RemoveProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_RemoveProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ExternalPSKProposal(ctx context.Context, in *ExternalPSKProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_ExternalPSKProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ResumptionPSKProposal(ctx context.Context, in *ResumptionPSKProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_ResumptionPSKProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) GroupContextExtensionsProposal(ctx context.Context, in *GroupContextExtensionsProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_GroupContextExtensionsProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) Commit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_Commit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandleCommit(ctx context.Context, in *HandleCommitRequest, opts ...grpc.CallOption) (*HandleCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleCommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandleCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandlePendingCommit(ctx context.Context, in *HandlePendingCommitRequest, opts ...grpc.CallOption) (*HandleCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleCommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandlePendingCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ReInitProposal(ctx context.Context, in *ReInitProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_ReInitProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ReInitCommit(ctx context.Context, in *CommitRequest, opts ...grpc.CallOption) (*CommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_ReInitCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandlePendingReInitCommit(ctx context.Context, in *HandlePendingCommitRequest, opts ...grpc.CallOption) (*HandleReInitCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleReInitCommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandlePendingReInitCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandleReInitCommit(ctx context.Context, in *HandleCommitRequest, opts ...grpc.CallOption) (*HandleReInitCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleReInitCommitResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandleReInitCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ReInitWelcome(ctx context.Context, in *ReInitWelcomeRequest, opts ...grpc.CallOption) (*CreateSubgroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubgroupResponse)
	err := c.cc.Invoke(ctx, MLSClient_ReInitWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandleReInitWelcome(ctx context.Context, in *HandleReInitWelcomeRequest, opts ...grpc.CallOption) (*JoinGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinGroupResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandleReInitWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) CreateBranch(ctx context.Context, in *CreateBranchRequest, opts ...grpc.CallOption) (*CreateSubgroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubgroupResponse)
	err := c.cc.Invoke(ctx, MLSClient_CreateBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) HandleBranch(ctx context.Context, in *HandleBranchRequest, opts ...grpc.CallOption) (*HandleBranchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandleBranchResponse)
	err := c.cc.Invoke(ctx, MLSClient_HandleBranch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) NewMemberAddProposal(ctx context.Context, in *NewMemberAddProposalRequest, opts ...grpc.CallOption) (*NewMemberAddProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NewMemberAddProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_NewMemberAddProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) CreateExternalSigner(ctx context.Context, in *CreateExternalSignerRequest, opts ...grpc.CallOption) (*CreateExternalSignerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateExternalSignerResponse)
	err := c.cc.Invoke(ctx, MLSClient_CreateExternalSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) AddExternalSigner(ctx context.Context, in *AddExternalSignerRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_AddExternalSigner_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) ExternalSignerProposal(ctx context.Context, in *ExternalSignerProposalRequest, opts ...grpc.CallOption) (*ProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProposalResponse)
	err := c.cc.Invoke(ctx, MLSClient_ExternalSignerProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSClientClient) Free(ctx context.Context, in *FreeRequest, opts ...grpc.CallOption) (*FreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FreeResponse)
	err := c.cc.Invoke(ctx, MLSClient_Free_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLSClientServer is the server API for MLSClient service.
// All implementations must embed UnimplementedMLSClientServer
// for forward compatibility.
//
// A wrapper around an MLS client implementation
type MLSClientServer interface {
	// The human-readable name of the stack
	Name(context.Context, *NameRequest) (*NameResponse, error)
	// List of supported ciphersuites
	SupportedCiphersuites(context.Context, *SupportedCiphersuitesRequest) (*SupportedCiphersuitesResponse, error)
	// Ways to become a member of a group
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	CreateKeyPackage(context.Context, *CreateKeyPackageRequest) (*CreateKeyPackageResponse, error)
	JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error)
	ExternalJoin(context.Context, *ExternalJoinRequest) (*ExternalJoinResponse, error)
	// Operations using a group state
	GroupInfo(context.Context, *GroupInfoRequest) (*GroupInfoResponse, error)
	StateAuth(context.Context, *StateAuthRequest) (*StateAuthResponse, error)
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	Protect(context.Context, *ProtectRequest) (*ProtectResponse, error)
	Unprotect(context.Context, *UnprotectRequest) (*UnprotectResponse, error)
	StorePSK(context.Context, *StorePSKRequest) (*StorePSKResponse, error)
	AddProposal(context.Context, *AddProposalRequest) (*ProposalResponse, error)
	UpdateProposal(context.Context, *UpdateProposalRequest) (*ProposalResponse, error)
	RemoveProposal(context.Context, *RemoveProposalRequest) (*ProposalResponse, error)
	ExternalPSKProposal(context.Context, *ExternalPSKProposalRequest) (*ProposalResponse, error)
	ResumptionPSKProposal(context.Context, *ResumptionPSKProposalRequest) (*ProposalResponse, error)
	GroupContextExtensionsProposal(context.Context, *GroupContextExtensionsProposalRequest) (*ProposalResponse, error)
	Commit(context.Context, *CommitRequest) (*CommitResponse, error)
	HandleCommit(context.Context, *HandleCommitRequest) (*HandleCommitResponse, error)
	HandlePendingCommit(context.Context, *HandlePendingCommitRequest) (*HandleCommitResponse, error)
	// Reinitialization
	ReInitProposal(context.Context, *ReInitProposalRequest) (*ProposalResponse, error)
	ReInitCommit(context.Context, *CommitRequest) (*CommitResponse, error)
	HandlePendingReInitCommit(context.Context, *HandlePendingCommitRequest) (*HandleReInitCommitResponse, error)
	HandleReInitCommit(context.Context, *HandleCommitRequest) (*HandleReInitCommitResponse, error)
	ReInitWelcome(context.Context, *ReInitWelcomeRequest) (*CreateSubgroupResponse, error)
	HandleReInitWelcome(context.Context, *HandleReInitWelcomeRequest) (*JoinGroupResponse, error)
	// Subgroup Branching
	CreateBranch(context.Context, *CreateBranchRequest) (*CreateSubgroupResponse, error)
	HandleBranch(context.Context, *HandleBranchRequest) (*HandleBranchResponse, error)
	// External proposals
	NewMemberAddProposal(context.Context, *NewMemberAddProposalRequest) (*NewMemberAddProposalResponse, error)
	CreateExternalSigner(context.Context, *CreateExternalSignerRequest) (*CreateExternalSignerResponse, error)
	AddExternalSigner(context.Context, *AddExternalSignerRequest) (*ProposalResponse, error)
	ExternalSignerProposal(context.Context, *ExternalSignerProposalRequest) (*ProposalResponse, error)
	// Cleanup
	Free(context.Context, *FreeRequest) (*FreeResponse, error)
	mustEmbedUnimplementedMLSClientServer()
}

// UnimplementedMLSClientServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLSClientServer struct{}

func (UnimplementedMLSClientServer) Name(context.Context, *NameRequest) (*NameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Name not implemented")
}
func (UnimplementedMLSClientServer) SupportedCiphersuites(context.Context, *SupportedCiphersuitesRequest) (*SupportedCiphersuitesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SupportedCiphersuites not implemented")
}
func (UnimplementedMLSClientServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedMLSClientServer) CreateKeyPackage(context.Context, *CreateKeyPackageRequest) (*CreateKeyPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateKeyPackage not implemented")
}
func (UnimplementedMLSClientServer) JoinGroup(context.Context, *JoinGroupRequest) (*JoinGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinGroup not implemented")
}
func (UnimplementedMLSClientServer) ExternalJoin(context.Context, *ExternalJoinRequest) (*ExternalJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExternalJoin not implemented")
}
func (UnimplementedMLSClientServer) GroupInfo(context.Context, *GroupInfoRequest) (*GroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupInfo not implemented")
}
func (UnimplementedMLSClientServer) StateAuth(context.Context, *StateAuthRequest) (*StateAuthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StateAuth not implemented")
}
func (UnimplementedMLSClientServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedMLSClientServer) Protect(context.Context, *ProtectRequest) (*ProtectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Protect not implemented")
}
func (UnimplementedMLSClientServer) Unprotect(context.Context, *UnprotectRequest) (*UnprotectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unprotect not implemented")
}
func (UnimplementedMLSClientServer) StorePSK(context.Context, *StorePSKRequest) (*StorePSKResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StorePSK not implemented")
}
func (UnimplementedMLSClientServer) AddProposal(context.Context, *AddProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddProposal not implemented")
}
func (UnimplementedMLSClientServer) UpdateProposal(context.Context, *UpdateProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProposal not implemented")
}
func (UnimplementedMLSClientServer) RemoveProposal(context.Context, *RemoveProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveProposal not implemented")
}
func (UnimplementedMLSClientServer) ExternalPSKProposal(context.Context, *ExternalPSKProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExternalPSKProposal not implemented")
}
func (UnimplementedMLSClientServer) ResumptionPSKProposal(context.Context, *ResumptionPSKProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumptionPSKProposal not implemented")
}
func (UnimplementedMLSClientServer) GroupContextExtensionsProposal(context.Context, *GroupContextExtensionsProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GroupContextExtensionsProposal not implemented")
}
func (UnimplementedMLSClientServer) Commit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Commit not implemented")
}
func (UnimplementedMLSClientServer) HandleCommit(context.Context, *HandleCommitRequest) (*HandleCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleCommit not implemented")
}
func (UnimplementedMLSClientServer) HandlePendingCommit(context.Context, *HandlePendingCommitRequest) (*HandleCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePendingCommit not implemented")
}
func (UnimplementedMLSClientServer) ReInitProposal(context.Context, *ReInitProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReInitProposal not implemented")
}
func (UnimplementedMLSClientServer) ReInitCommit(context.Context, *CommitRequest) (*CommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReInitCommit not implemented")
}
func (UnimplementedMLSClientServer) HandlePendingReInitCommit(context.Context, *HandlePendingCommitRequest) (*HandleReInitCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandlePendingReInitCommit not implemented")
}
func (UnimplementedMLSClientServer) HandleReInitCommit(context.Context, *HandleCommitRequest) (*HandleReInitCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleReInitCommit not implemented")
}
func (UnimplementedMLSClientServer) ReInitWelcome(context.Context, *ReInitWelcomeRequest) (*CreateSubgroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReInitWelcome not implemented")
}
func (UnimplementedMLSClientServer) HandleReInitWelcome(context.Context, *HandleReInitWelcomeRequest) (*JoinGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleReInitWelcome not implemented")
}
func (UnimplementedMLSClientServer) CreateBranch(context.Context, *CreateBranchRequest) (*CreateSubgroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateBranch not implemented")
}
func (UnimplementedMLSClientServer) HandleBranch(context.Context, *HandleBranchRequest) (*HandleBranchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleBranch not implemented")
}
func (UnimplementedMLSClientServer) NewMemberAddProposal(context.Context, *NewMemberAddProposalRequest) (*NewMemberAddProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NewMemberAddProposal not implemented")
}
func (UnimplementedMLSClientServer) CreateExternalSigner(context.Context, *CreateExternalSignerRequest) (*CreateExternalSignerResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateExternalSigner not implemented")
}
func (UnimplementedMLSClientServer) AddExternalSigner(context.Context, *AddExternalSignerRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddExternalSigner not implemented")
}
func (UnimplementedMLSClientServer) ExternalSignerProposal(context.Context, *ExternalSignerProposalRequest) (*ProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExternalSignerProposal not implemented")
}
func (UnimplementedMLSClientServer) Free(context.Context, *FreeRequest) (*FreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Free not implemented")
}
func (UnimplementedMLSClientServer) mustEmbedUnimplementedMLSClientServer() {}
func (UnimplementedMLSClientServer) testEmbeddedByValue()                   {}

// UnsafeMLSClientServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLSClientServer will
// result in compilation errors.
type UnsafeMLSClientServer interface {
	mustEmbedUnimplementedMLSClientServer()
}

func RegisterMLSClientServer(s grpc.ServiceRegistrar, srv MLSClientServer) {
	// If the following call panics, it indicates UnimplementedMLSClientServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLSClient_ServiceDesc, srv)
}

func _MLSClient_Name_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Name(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Name_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Name(ctx, req.(*NameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_SupportedCiphersuites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SupportedCiphersuitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).SupportedCiphersuites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_SupportedCiphersuites_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).SupportedCiphersuites(ctx, req.(*SupportedCiphersuitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_CreateKeyPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateKeyPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).CreateKeyPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_CreateKeyPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).CreateKeyPackage(ctx, req.(*CreateKeyPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_JoinGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).JoinGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_JoinGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).JoinGroup(ctx, req.(*JoinGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ExternalJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ExternalJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ExternalJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ExternalJoin(ctx, req.(*ExternalJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_GroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).GroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_GroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).GroupInfo(ctx, req.(*GroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_StateAuth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StateAuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).StateAuth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_StateAuth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).StateAuth(ctx, req.(*StateAuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_Protect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProtectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Protect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Protect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Protect(ctx, req.(*ProtectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_Unprotect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnprotectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Unprotect(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Unprotect_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Unprotect(ctx, req.(*UnprotectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_StorePSK_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StorePSKRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).StorePSK(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_StorePSK_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).StorePSK(ctx, req.(*StorePSKRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_AddProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).AddProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_AddProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).AddProposal(ctx, req.(*AddProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_UpdateProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).UpdateProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_UpdateProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).UpdateProposal(ctx, req.(*UpdateProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_RemoveProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).RemoveProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_RemoveProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).RemoveProposal(ctx, req.(*RemoveProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ExternalPSKProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalPSKProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ExternalPSKProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ExternalPSKProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ExternalPSKProposal(ctx, req.(*ExternalPSKProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ResumptionPSKProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumptionPSKProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ResumptionPSKProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ResumptionPSKProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ResumptionPSKProposal(ctx, req.(*ResumptionPSKProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_GroupContextExtensionsProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GroupContextExtensionsProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).GroupContextExtensionsProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_GroupContextExtensionsProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).GroupContextExtensionsProposal(ctx, req.(*GroupContextExtensionsProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_Commit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Commit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Commit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Commit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandleCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandleCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandleCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandleCommit(ctx, req.(*HandleCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandlePendingCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlePendingCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandlePendingCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandlePendingCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandlePendingCommit(ctx, req.(*HandlePendingCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ReInitProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReInitProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ReInitProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ReInitProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ReInitProposal(ctx, req.(*ReInitProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ReInitCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ReInitCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ReInitCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ReInitCommit(ctx, req.(*CommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandlePendingReInitCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandlePendingCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandlePendingReInitCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandlePendingReInitCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandlePendingReInitCommit(ctx, req.(*HandlePendingCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandleReInitCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandleReInitCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandleReInitCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandleReInitCommit(ctx, req.(*HandleCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ReInitWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReInitWelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ReInitWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ReInitWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ReInitWelcome(ctx, req.(*ReInitWelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandleReInitWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleReInitWelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandleReInitWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandleReInitWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandleReInitWelcome(ctx, req.(*HandleReInitWelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_CreateBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).CreateBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_CreateBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).CreateBranch(ctx, req.(*CreateBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_HandleBranch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleBranchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).HandleBranch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_HandleBranch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).HandleBranch(ctx, req.(*HandleBranchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_NewMemberAddProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewMemberAddProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).NewMemberAddProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_NewMemberAddProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).NewMemberAddProposal(ctx, req.(*NewMemberAddProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_CreateExternalSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateExternalSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).CreateExternalSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_CreateExternalSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).CreateExternalSigner(ctx, req.(*CreateExternalSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_AddExternalSigner_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddExternalSignerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).AddExternalSigner(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_AddExternalSigner_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).AddExternalSigner(ctx, req.(*AddExternalSignerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_ExternalSignerProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalSignerProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).ExternalSignerProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_ExternalSignerProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).ExternalSignerProposal(ctx, req.(*ExternalSignerProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSClient_Free_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSClientServer).Free(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSClient_Free_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSClientServer).Free(ctx, req.(*FreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLSClient_ServiceDesc is the grpc.ServiceDesc for MLSClient service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLSClient_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mls_client.MLSClient",
	HandlerType: (*MLSClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Name",
			Handler:    _MLSClient_Name_Handler,
		},
		{
			MethodName: "SupportedCiphersuites",
			Handler:    _MLSClient_SupportedCiphersuites_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _MLSClient_CreateGroup_Handler,
		},
		{
			MethodName: "CreateKeyPackage",
			Handler:    _MLSClient_CreateKeyPackage_Handler,
		},
		{
			MethodName: "JoinGroup",
			Handler:    _MLSClient_JoinGroup_Handler,
		},
		{
			MethodName: "ExternalJoin",
			Handler:    _MLSClient_ExternalJoin_Handler,
		},
		{
			MethodName: "GroupInfo",
			Handler:    _MLSClient_GroupInfo_Handler,
		},
		{
			MethodName: "StateAuth",
			Handler:    _MLSClient_StateAuth_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _MLSClient_Export_Handler,
		},
		{
			MethodName: "Protect",
			Handler:    _MLSClient_Protect_Handler,
		},
		{
			MethodName: "Unprotect",
			Handler:    _MLSClient_Unprotect_Handler,
		},
		{
			MethodName: "StorePSK",
			Handler:    _MLSClient_StorePSK_Handler,
		},
		{
			MethodName: "AddProposal",
			Handler:    _MLSClient_AddProposal_Handler,
		},
		{
			MethodName: "UpdateProposal",
			Handler:    _MLSClient_UpdateProposal_Handler,
		},
		{
			MethodName: "RemoveProposal",
			Handler:    _MLSClient_RemoveProposal_Handler,
		},
		{
			MethodName: "ExternalPSKProposal",
			Handler:    _MLSClient_ExternalPSKProposal_Handler,
		},
		{
			MethodName: "ResumptionPSKProposal",
			Handler:    _MLSClient_ResumptionPSKProposal_Handler,
		},
		{
			MethodName: "GroupContextExtensionsProposal",
			Handler:    _MLSClient_GroupContextExtensionsProposal_Handler,
		},
		{
			MethodName: "Commit",
			Handler:    _MLSClient_Commit_Handler,
		},
		{
			MethodName: "HandleCommit",
			Handler:    _MLSClient_HandleCommit_Handler,
		},
		{
			MethodName: "HandlePendingCommit",
			Handler:    _MLSClient_HandlePendingCommit_Handler,
		},
		{
			MethodName: "ReInitProposal",
			Handler:    _MLSClient_ReInitProposal_Handler,
		},
		{
			MethodName: "ReInitCommit",
			Handler:    _MLSClient_ReInitCommit_Handler,
		},
		{
			MethodName: "HandlePendingReInitCommit",
			Handler:    _MLSClient_HandlePendingReInitCommit_Handler,
		},
		{
			MethodName: "HandleReInitCommit",
			Handler:    _MLSClient_HandleReInitCommit_Handler,
		},
		{
			MethodName: "ReInitWelcome",
			Handler:    _MLSClient_ReInitWelcome_Handler,
		},
		{
			MethodName: "HandleReInitWelcome",
			Handler:    _MLSClient_HandleReInitWelcome_Handler,
		},
		{
			MethodName: "CreateBranch",
			Handler:    _MLSClient_CreateBranch_Handler,
		},
		{
			MethodName: "HandleBranch",
			Handler:    _MLSClient_HandleBranch_Handler,
		},
		{
			MethodName: "NewMemberAddProposal",
			Handler:    _MLSClient_NewMemberAddProposal_Handler,
		},
		{
			MethodName: "CreateExternalSigner",
			Handler:    _MLSClient_CreateExternalSigner_Handler,
		},
		{
			MethodName: "AddExternalSigner",
			Handler:    _MLSClient_AddExternalSigner_Handler,
		},
		{
			MethodName: "ExternalSignerProposal",
			Handler:    _MLSClient_ExternalSignerProposal_Handler,
		},
		{
			MethodName: "Free",
			Handler:    _MLSClient_Free_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls_client.proto",
}
